Exercise.create(name: "Bicycling", target_area: "Quadriceps", category: "Cardio")
Exercise.create(name: "Mountain Climbers", target_area: "Quadriceps", category: "Cardio")
Exercise.create(name: "Star Jump", target_area: "Quadriceps", category: "Cardio")
Exercise.create(name: "Jack and Jill Plank", target_area: "Abdominal (Core)", category: "Cardio")
Exercise.create(name: "Jump Rope", target_area: "Quadriceps, Hamstrings, Glutes, Calves (Legs)", category: "Cardio")
Exercise.create(name: "Single Arm Kettlebell Push Press", target_area: "Deltoids (Shoulders), Triceps (Arms)", category: "Cardio")
Exercise.create(name: "Bear Crawl", target_area: "Full Body", category: "Cardio")
Exercise.create(name: "Bear Plank Shoulder Tap", target_area: "Full Body", category: "Cardio")
Exercise.create(name: "High Knee", target_area: "Legs", category: "Cardio")
Exercise.create(name: "Jump Squat", target_area: "Quadriceps (Legs)", category: "Cardio")
