Exercise.create(name: "Chin to Chest", target_area: "Neck", category: "Stretch")
Exercise.create(name: "Child's Pose", target_area: "Lower Back", category: "Stretch")
Exercise.create(name: "Knee Across Body", target_area: "Glutes", category: "Stretch")
Exercise.create(name: "Knee to Chest", target_area: "Glutes", category: "Stretch")
Exercise.create(name: "Peroneals Stretch", target_area: "Calves (Legs)", category: "Stretch")
Exercise.create(name: "Standing Toe Touch", target_area: "Hamstrings (Legs)", category: "Stretch")
Exercise.create(name: "Cat Cow", target_area: "Back", category: "Stretch")
Exercise.create(name: "Bird Dog", target_area: "Back, Glutes, Abdominal (Core)", category: "Stretch")
Exercise.create(name: "Banded Pull Apart", target_area: "Deltoids (Shoulders)", category: "Stretch")
Exercise.create(name: "Lying Pectoral Stretch", target_area: "Pectorals (Chest)", category: "Stretch")
Exercise.create(name: "Cross Body Shoulder Stretch", target_area: "Deltoids (Shoulders)", category: "Stretch")
Exercise.create(name: "Reclined Spinal Twist", target_area: "Back", category: "Stretch")
