Exercise.create(name: "Ab Crunch Machine", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "Alternate Hammer Curl", target_area: "Biceps (Arms)", category: "Strength")
Exercise.create(name: "Alternating Cable Shoulder Press", target_area: "Deltoids (Deltoids (Shoulders))", category: "Strength")
Exercise.create(name: "Alternating Kettlebell Row", target_area: "Middle Back", category: "Strength")
Exercise.create(name: "Arnold Dumbbell Press", target_area: "Deltoids (Shoulders)", category: "Strength")
Exercise.create(name: "Around the Worlds", target_area: "Pectorals (Chest)", category: "Strength")
Exercise.create(name: "Balance Board", target_area: "Calves (Legs)", category: "Strength")
Exercise.create(name: "Band Assisted Pull Ups", target_area: "Latissimus Dorsi (Back)", category: "Strength")
Exercise.create(name: "Banded Good Mornings", target_area: "Hamstrings (Legs)", category: "Strength")
Exercise.create(name: "Band Pull Apart", target_area: "Deltoids (Shoulders)", category: "Strength")
Exercise.create(name: "Barbell Bench Press", target_area: "Pectorals (Chest)", category: "Strength")
Exercise.create(name: "Barbell Deadlift", target_area: "Quadriceps, Hamstrings, Adductors (Legs)", category: "Strength")
Exercise.create(name: "Barbell Hip Thrust", target_area: "Glutes", category: "Strength")
Exercise.create(name: "Barbell Side Split Squat", target_area: "Quadriceps, Glutes (Legs)", category: "Strength")
Exercise.create(name: "Barbell Squat", target_area: "Quadriceps, Glutes (Legs)", category: "Strength")
Exercise.create(name: "Bear Crawl Sled Drags", target_area: "Quadriceps (Legs)", category: "Strength")
Exercise.create(name: "Bench Dips", target_area: "Triceps (Arms)", category: "Strength")
Exercise.create(name: "Bent Over Row", target_area: "Middle Back", category: "Strength")
Exercise.create(name: "Cable Hammer Curls", target_area: "Biceps (Arms)", category: "Strength")
Exercise.create(name: "Cable Incline Pushdown", target_area: "Latissimus Dorsi (Back)", category: "Strength")
Exercise.create(name: "Cable Seated Lateral Raise", target_area: "Deltoids (Shoulders)", category: "Strength")
Exercise.create(name: "Calf Press (on leg press)", target_area: "Calves (Legs)", category: "Strength")
Exercise.create(name: "Calf Raises (w/ or w/o dumbbells/bands)", target_area: "Calves (Legs)", category: "Strength")
Exercise.create(name: "Clean Shrug", target_area: "Trapezius (Back/Shoulders)", category: "Strength")
Exercise.create(name: "Close Grip Dumbbell Press", target_area: "Triceps (Arms)", category: "Strength")
Exercise.create(name: "Cross Body Hammer Curl", target_area: "Biceps (Arms)", category: "Strength")
Exercise.create(name: "Cross Body Crunch", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "Drag Curl", target_area: "Biceps (Arms)", category: "Strength")
Exercise.create(name: "Dumbbell Chest Fly", target_area: "Pectorals (Chest)", category: "Strength")
Exercise.create(name: "Dumbbell Side Bend", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "Dumbbell Tricep Extension (Single Arm)", target_area: "Triceps (Arms)", category: "Strength")
Exercise.create(name: "Face Pull", target_area: "Rear Deltoids (Shoulders)", category: "Strength")
Exercise.create(name: "Frog Sit Ups", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "Front Leg Raise", target_area: "Hamstrings (Legs)", category: "Strength")
Exercise.create(name: "Front Plate Raise", target_area: "Rear Deltoids (Shoulders)", category: "Strength")
Exercise.create(name: "Glute Kickback", target_area: "Glutes", category: "Strength")
Exercise.create(name: "Goblet Squat", target_area: "Quadriceps (Legs)", category: "Strength")
Exercise.create(name: "Incline Bench Pull", target_area: "Middle Back", category: "Strength")
Exercise.create(name: "Jackknife Sit Up", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "Lateral Raise", target_area: "Lateral Deltoids (Shoulders)", category: "Strength")
Exercise.create(name: "Leg Extension", target_area: "Quadriceps (Legs)", category: "Strength")
Exercise.create(name: "Monster Walk", target_area: "Abductors (Legs)", category: "Strength")
Exercise.create(name: "Oblique Crunch", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "One Legged Cable Kickback", target_area: "Glutes", category: "Strength")
Exercise.create(name: "Overhead Slam", target_area: "Latissimus Dorsi (Back)", category: "Strength")
Exercise.create(name: "Plank", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "Plyo Push-Up", target_area: "Pectorals (Chest)", category: "Strength")
Exercise.create(name: "Power Clean", target_area: "Hamstrings (Legs)", category: "Strength")
Exercise.create(name: "Power Partial", target_area: "Deltoids (Shoulders)", category: "Strength")
Exercise.create(name: "Pull Through", target_area: "Glutes", category: "Strength")
Exercise.create(name: "Pull Up", target_area: "Latissimus Dorsi (Back)", category: "Strength")
Exercise.create(name: "Push Up", target_area: "Pectorals (Chest)", category: "Strength")
Exercise.create(name: "Reverse Crunch", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "Romanian Deadlift", target_area: "Hamstrings (Legs)", category: "Strength")
Exercise.create(name: "Russian Twist", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "Scissor Jump", target_area: "Quadriceps (Legs)", category: "Strength")
Exercise.create(name: "Sit Up", target_area: "Abdominal (Core)", category: "Strength")
Exercise.create(name: "Sled Drag", target_area: "Quadriceps (Legs)", category: "Strength")
Exercise.create(name: "Squat", target_area: "Quadriceps, Glutes (Legs)", category: "Strength")
Exercise.create(name: "Superman", target_area: "Lower Back, Glutes", category: "Strength")
Exercise.create(name: "Tricep Dumbbell Kickback", target_area: "Triceps (Arms)", category: "Strength")
Exercise.create(name: "Underhand Cable Pulldown", target_area: "Latissimus Dorsi (Back)", category: "Strength")
Exercise.create(name: "Upright Row", target_area: "Trapezius (Back/Shoulders)", category: "Strength")


Exercise.create(name: "Chin to Chest", target_area: "Neck", category: "Stretch")
Exercise.create(name: "Child's Pose", target_area: "Lower Back", category: "Stretch")
Exercise.create(name: "Knee Across Body", target_area: "Glutes", category: "Stretch")
Exercise.create(name: "Knee to Chest", target_area: "Glutes", category: "Stretch")
Exercise.create(name: "Peroneals Stretch", target_area: "Calves (Legs)", category: "Stretch")
Exercise.create(name: "Standing Toe Touch", target_area: "Hamstrings (Legs)", category: "Stretch")
Exercise.create(name: "Cat Cow", target_area: "Back", category: "Stretch")
Exercise.create(name: "Bird Dog", target_area: "Back, Glutes, Abdominal (Core)", category: "Stretch")
Exercise.create(name: "Banded Pull Apart", target_area: "Deltoids (Shoulders)", category: "Stretch")
Exercise.create(name: "Lying Pectoral Stretch", target_area: "Pectorals (Chest)", category: "Stretch")
Exercise.create(name: "Cross Body Shoulder Stretch", target_area: "Deltoids (Shoulders)", category: "Stretch")
Exercise.create(name: "Reclined Spinal Twist", target_area: "Back", category: "Stretch")


Exercise.create(name: "Bicycling", target_area: "Quadriceps", category: "Cardio")
Exercise.create(name: "Mountain Climbers", target_area: "Quadriceps", category: "Cardio")
Exercise.create(name: "Star Jump", target_area: "Quadriceps", category: "Cardio")
Exercise.create(name: "Jack and Jill Plank", target_area: "Abdominal (Core)", category: "Cardio")
Exercise.create(name: "Jump Rope", target_area: "Quadriceps, Hamstrings, Glutes, Calves (Legs)", category: "Cardio")
Exercise.create(name: "Single Arm Kettlebell Push Press", target_area: "Deltoids (Shoulders), Triceps (Arms)", category: "Cardio")
Exercise.create(name: "Bear Crawl", target_area: "Full Body", category: "Cardio")
Exercise.create(name: "Bear Plank Shoulder Tap", target_area: "Full Body", category: "Cardio")
Exercise.create(name: "High Knee", target_area: "Legs", category: "Cardio")
Exercise.create(name: "Jump Squat", target_area: "Quadriceps (Legs)", category: "Cardio")




